import type { CardDef } from "./types";

export const CARDS: CardDef[] = [
  { id: "V001", name: "Chico", cls: "Crown", kind: "Creature", cost: 1, atk: 1, hp: 2, keywords: ["Taunt"], text: "Taunt." },
  { id: "V002", name: "Daisy", cls: "Bow", kind: "Creature", cost: 1, atk: 2, hp: 2, keywords: [], text: "A 2/2 Bow body." },
  { id: "V003", name: "Dash", cls: "Bow", kind: "Creature", cost: 1, atk: 2, hp: 1, keywords: ["Rush"], text: "Rush. Cannot hit the Hero the turn it enters." },
  { id: "V004", name: "Gary", cls: "Neutral", kind: "Creature", cost: 1, atk: 1, hp: 1, keywords: [], text: "Play: Draw a card.", play: [{ op: "draw", n: 1 }] },
  { id: "V005", name: "Ginger", cls: "Wizard", kind: "Creature", cost: 1, atk: 0, hp: 1, keywords: [], text: "Passive: At the end of your turn, draw a card.", end: [{ op: "draw", n: 1 }] },
  { id: "V006", name: "Icy", cls: "Neutral", kind: "Creature", cost: 1, atk: 0, hp: 2, keywords: [], text: "Passive: Your Hero is immune.", flags: ["heroImmune"] },
  { id: "V007", name: "Jones", cls: "Neutral", kind: "Creature", cost: 1, atk: 1, hp: 2, keywords: [], text: "Play: Shuffle your hand into your deck and draw that many.", play: [{ op: "shuffleHandRedraw" }] },
  { id: "V008", name: "Mini", cls: "All", kind: "Creature", cost: 1, atk: 1, hp: 2, keywords: [], text: "Counts as all classes.", flags: ["allClass"] },
  { id: "V009", name: "Poke", cls: "Wizard", kind: "Creature", cost: 1, atk: 1, hp: 1, keywords: [], text: "End: Deal 1 to the enemy Hero.", end: [{ op: "damage", n: 1, who: "enemyHero" }] },
  { id: "V010", name: "Prince", cls: "Crown", kind: "Creature", cost: 1, atk: 1, hp: 2, keywords: [], text: "Start: Draw a card.", start: [{ op: "draw", n: 1 }] },
  { id: "V011", name: "Pumpy", cls: "Zombie", kind: "Creature", cost: 2, atk: 3, hp: 2, keywords: [], text: "Haunt: Restore 3 HP.", haunt: [{ op: "heal", n: 3 }] },
  { id: "V012", name: "Stump", cls: "Pirate", kind: "Creature", cost: 1, atk: 1, hp: 2, keywords: [], text: "Passive: +2 ATK if you control another creature.", flags: ["stumpBuff"] },
  { id: "V013", name: "Thumpy", cls: "Zombie", kind: "Creature", cost: 1, atk: 0, hp: 2, keywords: ["Taunt"], text: "Taunt. Haunt: Draw a card.", haunt: [{ op: "draw", n: 1 }] },
  { id: "V014", name: "Web", cls: "Pirate", kind: "Creature", cost: 1, atk: 2, hp: 1, keywords: [], text: "Haunt: Draw a card.", haunt: [{ op: "draw", n: 1 }] },
  { id: "V015", name: "Blade", cls: "Pirate", kind: "Creature", cost: 2, atk: 3, hp: 2, keywords: [], text: "Haunt: Deal 2 to the enemy Hero.", haunt: [{ op: "damage", n: 2, who: "enemyHero" }] },
  { id: "V016", name: "Bone", cls: "Neutral", kind: "Creature", cost: 2, atk: 2, hp: 2, keywords: [], text: "Play: Banish a card from a graveyard.", play: [{ op: "banishGrave" }] },
  { id: "V017", name: "Chart", cls: "Pirate", kind: "Creature", cost: 2, atk: 2, hp: 3, keywords: [], text: "Play: Add a Pirate Spell from your deck.", play: [{ op: "addFromDeck", kind: "Spell", cls: "Pirate", n: 1 }] },
  { id: "V018", name: "Digger", cls: "Zombie", kind: "Creature", cost: 1, atk: 2, hp: 1, keywords: [], text: "Play: Send a creature from your deck to the grave.", play: [{ op: "millCreature" }] },
  { id: "V019", name: "Doom", cls: "Neutral", kind: "Creature", cost: 2, atk: 0, hp: 5, keywords: [], text: "Start: Destroy all creatures.", start: [{ op: "destroyAllCreatures" }] },
  { id: "V020", name: "Dumpy", cls: "Zombie", kind: "Creature", cost: 2, atk: 2, hp: 3, keywords: [], text: "Haunt: Deal 2 to the enemy Hero.", haunt: [{ op: "damage", n: 2, who: "enemyHero" }] },
  { id: "V021", name: "Flame", cls: "Neutral", kind: "Creature", cost: 2, atk: 2, hp: 1, keywords: [], text: "Play: Deal 2 to a target.", play: [{ op: "damage", n: 2, who: "any" }] },
  { id: "V022", name: "Helios", cls: "Crown", kind: "Creature", cost: 2, atk: 0, hp: 4, keywords: [], text: "Start: Deal 3 to the enemy Hero.", start: [{ op: "damage", n: 3, who: "enemyHero" }] },
  { id: "V023", name: "Hunter", cls: "Neutral", kind: "Creature", cost: 2, atk: 2, hp: 3, keywords: [], text: "Play: Destroy a trap or lasting spell.", play: [{ op: "destroyBackrow" }] },
  { id: "V024", name: "Loopy", cls: "Bow", kind: "Creature", cost: 2, atk: 1, hp: 3, keywords: ["Poison"], text: "Poison." },
  { id: "V025", name: "Midi", cls: "All", kind: "Creature", cost: 2, atk: 2, hp: 3, keywords: [], text: "Counts as all classes.", flags: ["allClass"] },
  { id: "V026", name: "Scroll", cls: "Wizard", kind: "Creature", cost: 2, atk: 2, hp: 3, keywords: [], text: "Play: Add a Wizard Spell from your deck.", play: [{ op: "addFromDeck", kind: "Spell", cls: "Wizard", n: 1 }] },
  { id: "V027", name: "Stone", cls: "Crown", kind: "Creature", cost: 2, atk: 2, hp: 3, keywords: ["Taunt"], text: "Taunt." },
  { id: "V028", name: "Sunny", cls: "Bow", kind: "Creature", cost: 2, atk: 2, hp: 3, keywords: [], text: "When an adjacent creature dies, draw a card.", flags: ["adjDeathDraw"] },
  { id: "V029", name: "Wayne", cls: "Neutral", kind: "Creature", cost: 2, atk: 4, hp: 1, keywords: ["Rush"], text: "Rush. Removed from online competitive play — overpowered.", banned: true },
  { id: "V030", name: "Champ", cls: "Crown", kind: "Creature", cost: 3, atk: 4, hp: 2, keywords: ["Taunt"], text: "Taunt. Haunt: Draw a card.", haunt: [{ op: "draw", n: 1 }] },
  { id: "V031", name: "Dusty", cls: "Pirate", kind: "Creature", cost: 3, atk: 3, hp: 3, keywords: [], text: "Adjacent creatures have Taunt.", flags: ["adjTaunt"] },
  { id: "V032", name: "Fitch", cls: "Zombie", kind: "Creature", cost: 3, atk: 3, hp: 3, keywords: [], text: "Play: Add a spell from your graveyard.", play: [{ op: "addFromGrave", kind: "Spell", n: 1 }] },
  { id: "V033", name: "Goji", cls: "Crown", kind: "Creature", cost: 3, atk: 3, hp: 3, keywords: [], text: "Adjacent start effects trigger twice.", flags: ["adjStartDouble"] },
  { id: "V034", name: "Mary", cls: "Bow", kind: "Creature", cost: 3, atk: 3, hp: 2, keywords: [], text: "Play: Deal 3 to a target.", play: [{ op: "damage", n: 3, who: "any" }] },
  { id: "V035", name: "Mega", cls: "All", kind: "Creature", cost: 3, atk: 3, hp: 4, keywords: [], text: "Counts as all classes.", flags: ["allClass"] },
  { id: "V036", name: "Plague", cls: "Neutral", kind: "Creature", cost: 3, atk: 2, hp: 4, keywords: [], text: "Enemy Hero cannot be healed.", flags: ["antiHeal"] },
  { id: "V037", name: "Scout", cls: "Pirate", kind: "Creature", cost: 3, atk: 2, hp: 4, keywords: [], text: "Adjacent creatures have Rush.", flags: ["adjRush"] },
  { id: "V038", name: "Shepherd", cls: "Zombie", kind: "Creature", cost: 3, atk: 2, hp: 2, keywords: [], text: "Play: Summon a 2-or-less from grave.", play: [{ op: "summonGrave", maxCost: 2, n: 1 }] },
  { id: "V039", name: "Skip", cls: "Wizard", kind: "Creature", cost: 3, atk: 3, hp: 3, keywords: [], text: "End: Restore 3 HP.", end: [{ op: "heal", n: 3 }] },
  { id: "V040", name: "Spark", cls: "Wizard", kind: "Creature", cost: 3, atk: 3, hp: 3, keywords: [], text: "End: Deal 2 to the enemy Hero.", end: [{ op: "damage", n: 2, who: "enemyHero" }] },
  { id: "V041", name: "Surge", cls: "Wizard", kind: "Creature", cost: 3, atk: 2, hp: 3, keywords: [], text: "Adjacent end effects trigger twice.", flags: ["adjEndDouble"] },
  { id: "V042", name: "Sweetie", cls: "Bow", kind: "Creature", cost: 3, atk: 2, hp: 2, keywords: [], text: "Play: Summon a 2-or-less from deck.", play: [{ op: "summonDeck", maxCost: 2, n: 1 }] },
  { id: "V043", name: "Yang", cls: "Neutral", kind: "Creature", cost: 3, atk: 2, hp: 1, keywords: [], text: "Play: Summon all copies of this from deck.", play: [{ op: "summonCopies" }] },
  { id: "V044", name: "Boogie", cls: "Zombie", kind: "Creature", cost: 4, atk: 4, hp: 4, keywords: [], text: "Play: Trigger Haunt of your other creatures.", play: [{ op: "hauntAllOthers" }] },
  { id: "V045", name: "Buster", cls: "Pirate", kind: "Creature", cost: 4, atk: 4, hp: 4, keywords: [], text: "Whenever another friendly creature dies, deal 2 to face.", flags: ["deathFace2"] },
  { id: "V046", name: "Cherry", cls: "Bow", kind: "Creature", cost: 4, atk: 3, hp: 3, keywords: [], text: "Play: Summon a 2-or-less from deck.", play: [{ op: "summonDeck", maxCost: 2, n: 1 }] },
  { id: "V047", name: "Houdini", cls: "Wizard", kind: "Creature", cost: 4, atk: 2, hp: 2, keywords: [], text: "Play: Summon up to two 2-or-less from deck.", play: [{ op: "summonDeck", maxCost: 2, n: 2 }] },
  { id: "V048", name: "Mama Light", cls: "Bow", kind: "Creature", cost: 4, atk: 4, hp: 4, keywords: [], text: "Play: Draw 1, or 2 if you control another creature.", play: [{ op: "draw", n: 1 }] },
  { id: "V049", name: "Mento", cls: "Wizard", kind: "Creature", cost: 4, atk: 4, hp: 4, keywords: ["Taunt"], text: "Taunt. Haunt: Draw a card.", haunt: [{ op: "draw", n: 1 }] },
  { id: "V050", name: "Pulse", cls: "Crown", kind: "Creature", cost: 4, atk: 4, hp: 4, keywords: [], text: "Start: Restore 5 HP.", start: [{ op: "heal", n: 5 }] },
  { id: "V051", name: "Reaper", cls: "Zombie", kind: "Creature", cost: 4, atk: 3, hp: 5, keywords: [], text: "End: Trigger Haunt of adjacent creatures.", flags: ["adjHauntEnd"] },
  { id: "V052", name: "Renza", cls: "Neutral", kind: "Creature", cost: 7, atk: 5, hp: 5, keywords: [], text: "Play: Add a spell, a trap, and a creature from deck.", play: [{ op: "addFromDeck", kind: "any", n: 3 }] },
  { id: "V053", name: "Seeker", cls: "Crown", kind: "Creature", cost: 4, atk: 4, hp: 2, keywords: [], text: "Play: Add a creature from deck.", play: [{ op: "addFromDeck", kind: "Creature", n: 1 }] },
  { id: "V054", name: "Shiboshi", cls: "Pirate", kind: "Creature", cost: 4, atk: 4, hp: 2, keywords: [], text: "Haunt: Destroy creatures that killed this in combat.", haunt: [{ op: "destroyCombatKillers" }] },
  { id: "V055", name: "Turbo", cls: "Neutral", kind: "Creature", cost: 4, atk: 4, hp: 3, keywords: [], text: "Play: Destroy an enemy Taunt.", play: [{ op: "destroyTaunt" }] },
  { id: "V056", name: "Bender", cls: "Zombie", kind: "Creature", cost: 5, atk: 5, hp: 3, keywords: [], text: "Play: Summon up to two 2-or-less from grave.", play: [{ op: "summonGrave", maxCost: 2, n: 2 }] },
  { id: "V057", name: "Gummy", cls: "Neutral", kind: "Creature", cost: 6, atk: 6, hp: 5, keywords: [], text: "Enemy cannot summon from grave.", flags: ["lockGrave"] },
  { id: "V058", name: "Shield", cls: "Crown", kind: "Creature", cost: 5, atk: 6, hp: 3, keywords: [], text: "Play: Add up to 2 creatures from grave to hand.", play: [{ op: "addFromGrave", kind: "Creature", n: 2 }] },
  { id: "V059", name: "Toot", cls: "Zombie", kind: "Creature", cost: 5, atk: 4, hp: 4, keywords: [], text: "Haunt: Deal 5 to the enemy Hero.", haunt: [{ op: "damage", n: 5, who: "enemyHero" }] },
  { id: "V060", name: "Volt", cls: "Wizard", kind: "Creature", cost: 5, atk: 5, hp: 3, keywords: [], text: "Play: Add up to 2 traps from deck.", play: [{ op: "addFromDeck", kind: "Trap", n: 2 }] },
  { id: "V061", name: "Cookie", cls: "Neutral", kind: "Creature", cost: 5, atk: 3, hp: 6, keywords: ["Taunt"], text: "Taunt. When enemy draws extra, you draw.", flags: ["punishExtraDraw"] },
  { id: "V062", name: "Mama Bark", cls: "Bow", kind: "Creature", cost: 5, atk: 4, hp: 4, keywords: [], text: "Play: Add up to 2 creatures from grave to hand.", play: [{ op: "addFromGrave", kind: "Creature", n: 2 }] },
  { id: "V063", name: "Penny", cls: "Pirate", kind: "Creature", cost: 6, atk: 6, hp: 2, keywords: [], text: "Play: Summon a 4-or-less from grave.", play: [{ op: "summonGrave", maxCost: 4, n: 1 }] },
  { id: "V064", name: "Aria", cls: "Bow", kind: "Creature", cost: 7, atk: 7, hp: 4, keywords: [], text: "Play: Deal 7 to a target.", play: [{ op: "damage", n: 7, who: "any" }] },
  { id: "V065", name: "Atlas", cls: "Crown", kind: "Creature", cost: 7, atk: 6, hp: 6, keywords: [], text: "Start: Deal 7 to the enemy Hero.", start: [{ op: "damage", n: 7, who: "enemyHero" }] },
  { id: "V066", name: "Manic", cls: "Neutral", kind: "Creature", cost: 7, atk: 5, hp: 4, keywords: [], text: "Play: Destroy an enemy creature.", play: [{ op: "destroyTarget" }] },
  { id: "V067", name: "Wiggles", cls: "Wizard", kind: "Creature", cost: 7, atk: 5, hp: 5, keywords: [], text: "End: Deal 5 to the enemy Hero.", end: [{ op: "damage", n: 5, who: "enemyHero" }] },
  { id: "V068", name: "Bamba", cls: "Neutral", kind: "Creature", cost: 8, atk: 8, hp: 8, keywords: [], text: "Enemy cannot summon or add from deck.", flags: ["lockDeck"] },
  { id: "V069", name: "Bark", cls: "Neutral", kind: "Creature", cost: 6, atk: 4, hp: 4, keywords: [], text: "Play: Shuffle a target into its owner's deck.", play: [{ op: "shuffleTargetDeck" }] },
  { id: "V070", name: "Barron", cls: "Pirate", kind: "Creature", cost: 8, atk: 7, hp: 5, keywords: [], text: "Play: Summon up to two 4-or-less from deck.", play: [{ op: "summonDeck", maxCost: 4, n: 2 }] },
  { id: "V071", name: "Gigatron", cls: "Neutral", kind: "Creature", cost: 10, atk: 10, hp: 10, keywords: [], text: "Play: Destroy all other cards in play.", play: [{ op: "destroyAllOther" }] },

  { id: "V072", name: "Boost", cls: "Neutral", kind: "Spell", cost: 1, atk: 0, hp: 0, keywords: [], text: "Play: Restore 8 HP.", play: [{ op: "heal", n: 8 }] },
  { id: "V073", name: "Frostbolt", cls: "Wizard", kind: "Spell", cost: 1, atk: 0, hp: 0, keywords: [], text: "Deal 1, or 3 if you control a Wizard.", play: [{ op: "damage", n: 1, who: "any" }] },
  { id: "V074", name: "Quickdraw", cls: "Neutral", kind: "Spell", cost: 1, atk: 0, hp: 0, keywords: [], text: "Draw a card.", play: [{ op: "draw", n: 1 }] },
  { id: "V075", name: "Sacrifice", cls: "Zombie", kind: "Spell", cost: 1, atk: 0, hp: 0, keywords: [], text: "Destroy a friendly creature, draw 2 (3 if Zombie).", play: [{ op: "destroyTarget" }, { op: "draw", n: 2 }] },
  { id: "V076", name: "Snake Venom", cls: "Pirate", kind: "Spell", cost: 1, atk: 0, hp: 0, keywords: [], text: "Give a friendly Pirate Poison this turn.", play: [{ op: "poisonPirate" }] },
  { id: "V077", name: "Typhoon", cls: "Neutral", kind: "Spell", cost: 1, atk: 0, hp: 0, keywords: [], text: "Destroy an enemy trap or lasting spell.", play: [{ op: "destroyBackrow" }] },
  { id: "V078", name: "Connection", cls: "Bow", kind: "Spell", cost: 2, atk: 0, hp: 0, keywords: [], text: "Add a Bow creature from deck.", play: [{ op: "addFromDeck", kind: "Creature", cls: "Bow", n: 1 }] },
  { id: "V079", name: "Cull", cls: "Neutral", kind: "Spell", cost: 2, atk: 0, hp: 0, keywords: [], text: "Destroy a creature with 3 or less ATK.", play: [{ op: "destroyAtkLte", n: 3 }] },
  { id: "V080", name: "Feast", cls: "Crown", kind: "Spell", cost: 2, atk: 0, hp: 0, keywords: [], text: "Passive lasting: start of turn heal 2 (4 with Crown).", flags: ["lasting", "feast"] },
  { id: "V081", name: "Fireball", cls: "Neutral", kind: "Spell", cost: 2, atk: 0, hp: 0, keywords: [], text: "Deal 3 to a target.", play: [{ op: "damage", n: 3, who: "any" }] },
  { id: "V082", name: "Haunted House", cls: "Zombie", kind: "Spell", cost: 3, atk: 0, hp: 0, keywords: [], text: "Lasting: end of turn, trigger Haunts you control.", flags: ["lasting", "hauntHouse"] },
  { id: "V083", name: "Love Bomb", cls: "Bow", kind: "Spell", cost: 2, atk: 0, hp: 0, keywords: [], text: "Restore 6, or 12 if you control a Bow.", play: [{ op: "heal", n: 6 }] },
  { id: "V084", name: "Love Shot", cls: "Bow", kind: "Spell", cost: 2, atk: 0, hp: 0, keywords: [], text: "Deal 2, or 4 if you control a Bow.", play: [{ op: "damage", n: 2, who: "any" }] },
  { id: "V085", name: "Pact", cls: "Zombie", kind: "Spell", cost: 2, atk: 0, hp: 0, keywords: [], text: "Destroy a friendly Zombie and an enemy creature.", play: [{ op: "destroyTarget" }] },
  { id: "V086", name: "Vanish", cls: "Neutral", kind: "Spell", cost: 2, atk: 0, hp: 0, keywords: [], text: "Return a creature to its owner's hand.", play: [{ op: "bounce" }] },
  { id: "V087", name: "Airdrop", cls: "Neutral", kind: "Spell", cost: 3, atk: 0, hp: 0, keywords: [], text: "Draw 2.", play: [{ op: "draw", n: 2 }] },
  { id: "V088", name: "Cauldron", cls: "Wizard", kind: "Spell", cost: 3, atk: 0, hp: 0, keywords: [], text: "Draw 1, or 3 if you control a Wizard.", play: [{ op: "draw", n: 1 }] },
  { id: "V089", name: "Chum The Water", cls: "Pirate", kind: "Spell", cost: 3, atk: 0, hp: 0, keywords: [], text: "Lasting: whenever a friendly Pirate dies, draw.", flags: ["lasting", "chum"] },
  { id: "V090", name: "Garden", cls: "Bow", kind: "Spell", cost: 3, atk: 0, hp: 0, keywords: [], text: "Lasting: Bow Play effects trigger twice.", flags: ["lasting", "garden"] },
  { id: "V091", name: "Judgement", cls: "Crown", kind: "Spell", cost: 3, atk: 0, hp: 0, keywords: [], text: "Deal 3, or 6 if you control a Crown.", play: [{ op: "damage", n: 3, who: "any" }] },
  { id: "V092", name: "Meditation", cls: "Crown", kind: "Spell", cost: 3, atk: 0, hp: 0, keywords: [], text: "Lasting: Crown start effects trigger twice.", flags: ["lasting", "meditation"] },
  { id: "V093", name: "Reborn", cls: "Zombie", kind: "Spell", cost: 3, atk: 0, hp: 0, keywords: [], text: "Summon a Zombie from grave.", play: [{ op: "summonGrave", maxCost: 99, n: 1, cls: "Zombie" }] },
  { id: "V094", name: "Scheme", cls: "Wizard", kind: "Spell", cost: 3, atk: 0, hp: 0, keywords: [], text: "Lasting: Wizard end effects trigger twice.", flags: ["lasting", "scheme"] },
  { id: "V095", name: "Spearfish", cls: "Pirate", kind: "Spell", cost: 3, atk: 0, hp: 0, keywords: [], text: "Bounce a creature, or destroy it if you control a Pirate.", play: [{ op: "bounce" }] },
  { id: "V096", name: "Takedown", cls: "Neutral", kind: "Spell", cost: 3, atk: 0, hp: 0, keywords: [], text: "Destroy a creature with 4+ ATK.", play: [{ op: "destroyAtkGte", n: 4 }] },
  { id: "V097", name: "Swipe", cls: "Neutral", kind: "Spell", cost: 6, atk: 0, hp: 0, keywords: [], text: "Two creatures fight each other.", play: [{ op: "swapAttack" }] },
  { id: "V098", name: "Avenge", cls: "Crown", kind: "Spell", cost: 5, atk: 0, hp: 0, keywords: [], text: "Summon up to two 3-or-less Crown from grave.", play: [{ op: "summonGrave", maxCost: 3, n: 2, cls: "Crown" }] },
  { id: "V099", name: "Booty Raid", cls: "Pirate", kind: "Spell", cost: 5, atk: 0, hp: 0, keywords: [], text: "Summon up to two 3-or-less Pirates from deck.", play: [{ op: "summonDeck", maxCost: 3, n: 2, cls: "Pirate" }] },
  { id: "V100", name: "Siphon", cls: "Wizard", kind: "Spell", cost: 5, atk: 0, hp: 0, keywords: [], text: "Destroy a creature. Heal 3 if you control a Wizard.", play: [{ op: "destroyTarget" }, { op: "heal", n: 3 }] },
  { id: "V101", name: "Black Hole", cls: "Neutral", kind: "Spell", cost: 7, atk: 0, hp: 0, keywords: [], text: "Destroy all creatures.", play: [{ op: "destroyAllCreatures" }] },
  { id: "V109", name: "Intel", cls: "Neutral", kind: "Spell", cost: 1, atk: 0, hp: 0, keywords: [], text: "Look at the opponent's hand.", play: [{ op: "lookHand" }] },

  { id: "V102", name: "Ambush", cls: "Neutral", kind: "Trap", cost: 2, atk: 0, hp: 0, keywords: [], text: "When an enemy creature attacks, negate and destroy it.", trap: { trigger: "enemyAttack", fx: [{ op: "negateAttackDestroy" }] } },
  { id: "V103", name: "Blast", cls: "Neutral", kind: "Trap", cost: 2, atk: 0, hp: 0, keywords: [], text: "When they would damage your Hero, reflect it.", trap: { trigger: "heroDamage", fx: [{ op: "reflectHeroDamage" }] } },
  { id: "V104", name: "Counterspell", cls: "Neutral", kind: "Trap", cost: 2, atk: 0, hp: 0, keywords: [], text: "When the enemy plays a spell, negate it.", trap: { trigger: "enemySpell", fx: [{ op: "negateSpell" }] } },
  { id: "V105", name: "Divine Shield", cls: "Neutral", kind: "Trap", cost: 2, atk: 0, hp: 0, keywords: [], text: "When they would destroy a friendly creature, negate it.", trap: { trigger: "friendlyDestroy", fx: [{ op: "saveCreature" }] } },
  { id: "V106", name: "Frost Lock", cls: "Neutral", kind: "Trap", cost: 2, atk: 0, hp: 0, keywords: [], text: "When your Hero takes fatal damage, negate and become immune this turn.", trap: { trigger: "fatalHero", fx: [{ op: "negateFatalImmune" }] } },
  { id: "V107", name: "Landmine", cls: "Neutral", kind: "Trap", cost: 2, atk: 0, hp: 0, keywords: [], text: "When they summon, destroy all creatures.", trap: { trigger: "enemySummon", fx: [{ op: "boardWipeOnSummon" }] } },
  { id: "V108", name: "Pitfall", cls: "Neutral", kind: "Trap", cost: 2, atk: 0, hp: 0, keywords: [], text: "When they summon a 4+ ATK creature, destroy it.", trap: { trigger: "enemySummonAtk4", fx: [{ op: "destroyHighSummon" }] } },
  { id: "V110", name: "Spring Trap", cls: "Neutral", kind: "Trap", cost: 2, atk: 0, hp: 0, keywords: [], text: "When they summon, bounce it to hand.", trap: { trigger: "enemySummon", fx: [{ op: "bounceSummon" }] } },
  { id: "V111", name: "Tidal Wave", cls: "Neutral", kind: "Trap", cost: 2, atk: 0, hp: 0, keywords: [], text: "After an enemy creature attacks your Hero, destroy all creatures.", trap: { trigger: "afterFaceAttack", fx: [{ op: "wipeAfterFace" }] } },
];

export const LEGAL_POOL = CARDS.filter((c) => !c.banned);

export function isLegalOnline(c: CardDef) {
  return !c.banned;
}

export const CARD_BY_ID: Record<string, CardDef> = Object.fromEntries(
  CARDS.map((c) => [c.id, c]),
);

export function defOf(id: string): CardDef {
  return (
    CARD_BY_ID[id] ?? {
      id,
      name: "Unknown",
      cls: "Neutral",
      kind: "Creature",
      cost: 0,
      atk: 0,
      hp: 1,
      keywords: [],
      text: "",
    }
  );
}

export const KEYWORDS = [
  { name: "Taunt", text: "Attacks must hit a Taunt first. Face and non-Taunt are closed." },
  { name: "Rush", text: "May attack creatures the turn it is played. Never the Hero that turn." },
  { name: "Poison", text: "Destroys the creature it fights even if ATK is lower. Does not ignore Hero HP." },
  { name: "Fury", text: "May attack twice per turn when ready." },
  { name: "Frozen", text: "Cannot attack. Lasts through the controller's next turn, then wears off." },
] as const;

export const RULES_TEXT = [
  { title: "Win", body: "Reduce the enemy Hero to 0 HP. Both 0 at once is a draw. Creatures have no life total that wins the game." },
  { title: "Open", body: "40 HP, 40-card deck, max 3 copies. Draw 4. Return every 5+ cost opener, shuffle, replace. Second player takes the Coin." },
  { title: "Mana", body: "Cap +1 each turn (max 10), refill to cap. Unspent mana does not bank. Coin pays +1 on one play and does not raise the cap." },
  { title: "Board", body: "Five creature lanes, one body each. Empty lanes stay empty. Five back-row slots for traps and lasting spells. Hand cap 10." },
  { title: "Kill-gate", body: "Creature fights are legal only if someone dies: ATK ≥ current HP, Poison, or a suicide trade. No chip. Stacking attackers is allowed. Heroes take numbered chip damage." },
  { title: "Traps", body: "Set face-down. Cannot spring the turn they are set. Next turn you may Spring or Hold when the trigger fires. Counters resolve left to right." },
  { title: "Fatigue", body: "Empty deck: 1, then 2, then 3… to the Hero each draw." },
];
