/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as ApiPackWatchExtDotzipRouteImport } from './routes/api/pack-watch-ext[.]zip'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPackWatchExtDotzipRoute = ApiPackWatchExtDotzipRouteImport.update({
  id: '/api/pack-watch-ext.zip',
  path: '/api/pack-watch-ext.zip',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/desk': typeof DeskRoute
  '/api/pack-watch-ext.zip': typeof ApiPackWatchExtDotzipRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/desk': typeof DeskRoute
  '/api/pack-watch-ext.zip': typeof ApiPackWatchExtDotzipRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/desk': typeof DeskRoute
  '/api/pack-watch-ext.zip': typeof ApiPackWatchExtDotzipRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/desk' | '/api/pack-watch-ext.zip'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/desk' | '/api/pack-watch-ext.zip'
  id: '__root__' | '/' | '/desk' | '/api/pack-watch-ext.zip'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeskRoute: typeof DeskRoute
  ApiPackWatchExtDotzipRoute: typeof ApiPackWatchExtDotzipRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pack-watch-ext.zip': {
      id: '/api/pack-watch-ext.zip'
      path: '/api/pack-watch-ext.zip'
      fullPath: '/api/pack-watch-ext.zip'
      preLoaderRoute: typeof ApiPackWatchExtDotzipRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeskRoute: DeskRoute,
  ApiPackWatchExtDotzipRoute: ApiPackWatchExtDotzipRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
