/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as ApiConsentRouteImport } from './routes/api/consent'
import { Route as ApiDdlCardsRouteImport } from './routes/api/ddl-cards'
import { Route as ApiPackWatchExtDotzipRouteImport } from './routes/api/pack-watch-ext[.]zip'
import { Route as ApiLearningShareRouteImport } from './routes/api/learning/share'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConsentRoute = ApiConsentRouteImport.update({
  id: '/api/consent',
  path: '/api/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDdlCardsRoute = ApiDdlCardsRouteImport.update({
  id: '/api/ddl-cards',
  path: '/api/ddl-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPackWatchExtDotzipRoute = ApiPackWatchExtDotzipRouteImport.update({
  id: '/api/pack-watch-ext.zip',
  path: '/api/pack-watch-ext.zip',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLearningShareRoute = ApiLearningShareRouteImport.update({
  id: '/api/learning/share',
  path: '/api/learning/share',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/desk': typeof DeskRoute
  '/api/consent': typeof ApiConsentRoute
  '/api/ddl-cards': typeof ApiDdlCardsRoute
  '/api/pack-watch-ext.zip': typeof ApiPackWatchExtDotzipRoute
  '/api/learning/share': typeof ApiLearningShareRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/desk': typeof DeskRoute
  '/api/consent': typeof ApiConsentRoute
  '/api/ddl-cards': typeof ApiDdlCardsRoute
  '/api/pack-watch-ext.zip': typeof ApiPackWatchExtDotzipRoute
  '/api/learning/share': typeof ApiLearningShareRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/desk': typeof DeskRoute
  '/api/consent': typeof ApiConsentRoute
  '/api/ddl-cards': typeof ApiDdlCardsRoute
  '/api/pack-watch-ext.zip': typeof ApiPackWatchExtDotzipRoute
  '/api/learning/share': typeof ApiLearningShareRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/desk'
    | '/api/consent'
    | '/api/ddl-cards'
    | '/api/pack-watch-ext.zip'
    | '/api/learning/share'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/desk'
    | '/api/consent'
    | '/api/ddl-cards'
    | '/api/pack-watch-ext.zip'
    | '/api/learning/share'
  id:
    | '__root__'
    | '/'
    | '/desk'
    | '/api/consent'
    | '/api/ddl-cards'
    | '/api/pack-watch-ext.zip'
    | '/api/learning/share'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeskRoute: typeof DeskRoute
  ApiConsentRoute: typeof ApiConsentRoute
  ApiDdlCardsRoute: typeof ApiDdlCardsRoute
  ApiPackWatchExtDotzipRoute: typeof ApiPackWatchExtDotzipRoute
  ApiLearningShareRoute: typeof ApiLearningShareRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/consent': {
      id: '/api/consent'
      path: '/api/consent'
      fullPath: '/api/consent'
      preLoaderRoute: typeof ApiConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ddl-cards': {
      id: '/api/ddl-cards'
      path: '/api/ddl-cards'
      fullPath: '/api/ddl-cards'
      preLoaderRoute: typeof ApiDdlCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pack-watch-ext.zip': {
      id: '/api/pack-watch-ext.zip'
      path: '/api/pack-watch-ext.zip'
      fullPath: '/api/pack-watch-ext.zip'
      preLoaderRoute: typeof ApiPackWatchExtDotzipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/learning/share': {
      id: '/api/learning/share'
      path: '/api/learning/share'
      fullPath: '/api/learning/share'
      preLoaderRoute: typeof ApiLearningShareRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeskRoute: DeskRoute,
  ApiConsentRoute: ApiConsentRoute,
  ApiDdlCardsRoute: ApiDdlCardsRoute,
  ApiPackWatchExtDotzipRoute: ApiPackWatchExtDotzipRoute,
  ApiLearningShareRoute: ApiLearningShareRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
